// Barer Brawl service worker — keeps returning players on the freshly deployed
// build instead of a stale, browser-cached one, and (since the PWA conversion)
// makes the installed app fully playable offline.
//
// Strategy: NETWORK-FIRST for every same-origin GET. On each load we fetch the
// real file from the network with `cache: 'reload'`, which bypasses the browser's
// HTTP disk cache. So the moment a new version is deployed, the next page load
// picks it up — no more running last visit's `main.js` against this visit's
// `director.js`. We still mirror successful responses into Cache Storage, and at
// install time we PRECACHE the whole app shell below, so the game works offline
// even for files the player never happened to load online.
//
// GitHub Pages sends `Cache-Control: max-age=600`, so without this a returning
// player could run up to ~10 minutes of stale code; this closes that window.

const CACHE_NAME = 'barer-brawl-v5';

// The complete app shell. Keep in sync when adding top-level files — a missing
// entry only degrades offline-before-first-fetch of that file, since the fetch
// handler mirrors everything it serves anyway.
const PRECACHE = [
  './',
  './index.html',
  './manifest.webmanifest',
  './css/style.css',
  './vendor/three.module.js',
  './src/assets.js',
  './src/audio.js',
  './src/vo-manifest.js',
  './src/characters.js',
  './src/collide.js',
  './src/chavrusa.js',
  './src/cutscene.js',
  './src/director.js',
  './src/dvartorah.js',
  './src/enemy.js',
  './src/finisher.js',
  './src/input.js',
  './src/main.js',
  './src/mapgen.js',
  './src/pathfind.js',
  './src/player.js',
  './src/props.js',
  './src/rng.js',
  './src/roombuilder.js',
  './src/textures.js',
  './src/touch.js',
  './src/ui.js',
  './assets/barer-default.png',
  './assets/barer-attack1.png',
  './assets/barer-attack2.png',
  './assets/barer-damaged.png',
  './assets/death.ogg',
  // Character voice-over (generated by tools/gen-vo.mjs; tolerated-missing at install
  // time until generated, so these can't break the precache — see the install handler).
  './assets/vo/intro-1.mp3',
  './assets/vo/intro-2.mp3',
  './assets/vo/intro-3.mp3',
  './assets/vo/intro-4.mp3',
  './assets/vo/intro-5.mp3',
  './assets/vo/intro-6.mp3',
  './assets/vo/dvar-1.mp3',
  './assets/vo/dvar-2.mp3',
  './assets/vo/dvar-3.mp3',
  './assets/vo/dvar-4.mp3',
  './assets/vo/dvar-5.mp3',
  './assets/vo/dvar-6.mp3',
  './assets/vo/dvar-7.mp3',
  './assets/vo/dvar-8.mp3',
  './assets/vo/dvar-9.mp3',
  './assets/vo/dvar-10.mp3',
  './assets/vo/dvar-11.mp3',
  './assets/vo/dvar-12.mp3',
  './assets/vo/dvar-13.mp3',
  './assets/vo/zehn-1.mp3',
  './assets/vo/zehn-2.mp3',
  './assets/vo/zehn-3.mp3',
  './assets/vo/zehn-4.mp3',
  './assets/vo/zehn-5.mp3',
  './assets/vo/zehn-6.mp3',
  './assets/vo/zehn-7.mp3',
  './assets/vo/zehn-8.mp3',
  './assets/vo/zehn-9.mp3',
  './assets/vo/zehn-10.mp3',
  './assets/vo/zehn-11.mp3',
  './assets/vo/zehn-12.mp3',
  './assets/vo/zehn-13.mp3',
  './assets/vo/finisher-lewie.mp3',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon-maskable-192.png',
  './icons/icon-maskable-512.png',
  './icons/apple-touch-icon.png',
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    // `reload` bypasses the HTTP cache so the precache is the deployed bytes,
    // not whatever the browser had lying around. Each entry is added independently
    // and individual failures are tolerated — a file that isn't in this build (e.g.
    // voice-over clips before `npm run gen-vo` has been run) can't abort the whole
    // install the way cache.addAll would; the fetch handler mirrors it later anyway.
    await Promise.all(PRECACHE.map(async (u) => {
      try { await cache.add(new Request(u, { cache: 'reload' })); } catch (e) { /* skip missing */ }
    }));
    // Don't wait for every other tab to close before this worker takes over.
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // Drop caches from any previous CACHE_NAME so nothing stale can linger.
    const names = await caches.keys();
    await Promise.all(names.map((n) => (n === CACHE_NAME ? null : caches.delete(n))));
    // Control already-open pages immediately (so their next fetch is network-first).
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // let cross-origin go straight to the network

  event.respondWith((async () => {
    try {
      // `reload` forces a network fetch that ignores (and refreshes) the HTTP cache.
      const fresh = await fetch(req, { cache: 'reload' });
      if (fresh && fresh.ok && fresh.type === 'basic') {
        const cache = await caches.open(CACHE_NAME);
        cache.put(req, fresh.clone());
      }
      return fresh;
    } catch (err) {
      // Offline / network error: fall back to the last copy we cached, if any.
      const cached = await caches.match(req, { ignoreSearch: req.mode === 'navigate' });
      if (cached) return cached;
      // An installed app launched offline navigates to start_url — make sure
      // that always resolves to the shell even if the exact URL wasn't cached.
      if (req.mode === 'navigate') {
        const shell = await caches.match('./index.html');
        if (shell) return shell;
      }
      throw err;
    }
  })());
});
